import type { Customer, Inquiry, Product, Reservation } from "@/types/domain";

export const categories = [
  "CFMOTO",
  "ZEEHO",
  "Lambretta",
  "Italjet",
  "Ducati",
  "Big Bikes",
  "Scooters",
  "Electric Motorcycles",
];

export const products: Product[] = [
  {
    id: "cfmoto-450sr-s-2026",
    sku: "VMH-BN-CFMOTO-450SR-S-2026",
    name: "2026 CFMOTO 450SR S",
    category: "CFMOTO",
    brand: "CFMOTO",
    model: "450SR S",
    condition: "Brand New",
    location: "Visayas Moto Hub Showroom",
    branch: "Cebu",
    status: "Ready",
    price: 299900,
    acquisitionCost: 0,
    quantity: 4,
    availableQuantity: 4,
    reservedQuantity: 0,
    description: "Brand-new sport motorcycle with showroom release support, warranty processing, and official dealer assistance.",
    imageUrl: "https://images.unsplash.com/photo-1558981359-219d6364c9c8?auto=format&fit=crop&w=1200&q=80",
    features: ["Brand new unit", "Official dealer support", "Warranty processing", "Showroom release"],
    specs: { Engine: "449cc", Power: "50 hp", Torque: "39 Nm", Gearbox: "6-speed", Fuel: "14 L", Weight: "179 kg" },
  },
  {
    id: "cfmoto-800nk-2026",
    sku: "VMH-BN-CFMOTO-800NK-2026",
    name: "2026 CFMOTO 800NK",
    category: "CFMOTO",
    brand: "CFMOTO",
    model: "800NK",
    condition: "Brand New",
    location: "Visayas Moto Hub Showroom",
    branch: "Cebu",
    status: "Ready",
    price: 488000,
    acquisitionCost: 0,
    quantity: 2,
    availableQuantity: 2,
    reservedQuantity: 0,
    description: "Brand-new naked sport motorcycle for riders who want daily usability with big-bike performance.",
    imageUrl: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80",
    features: ["Brand new unit", "Big-bike class", "Warranty processing", "Showroom release"],
    specs: { Engine: "799cc", Power: "99 hp", Torque: "79 Nm", Gearbox: "6-speed", Fuel: "15 L", Weight: "186 kg" },
  },
  {
    id: "zeeho-ae8-s-plus-2026",
    sku: "VMH-BN-ZEEHO-AE8S-2026",
    name: "2026 ZEEHO AE8 S+",
    category: "ZEEHO",
    brand: "ZEEHO",
    model: "AE8 S+",
    condition: "Brand New",
    location: "Visayas Moto Hub Showroom",
    branch: "Cebu",
    status: "Ready",
    price: 158000,
    acquisitionCost: 0,
    quantity: 5,
    availableQuantity: 5,
    reservedQuantity: 0,
    description: "Brand-new electric scooter with smart urban performance for daily Visayas commuting.",
    imageUrl: "https://images.unsplash.com/photo-1591637333184-19aa84b3e01f?auto=format&fit=crop&w=1200&q=80",
    features: ["Brand new unit", "Electric scooter", "Smart display", "Showroom release"],
    specs: { Engine: "Electric", Power: "12.5 kW", Torque: "218 Nm", Gearbox: "Automatic", Fuel: "Battery", Weight: "133 kg" },
  },
  {
    id: "lambretta-x300-2026",
    sku: "VMH-BN-LAMBRETTA-X300-2026",
    name: "2026 Lambretta X300",
    category: "Lambretta",
    brand: "Lambretta",
    model: "X300",
    condition: "Brand New",
    location: "Visayas Moto Hub Showroom",
    branch: "Cebu",
    status: "Ready",
    price: 318000,
    acquisitionCost: 0,
    quantity: 3,
    availableQuantity: 3,
    reservedQuantity: 0,
    description: "Brand-new premium scooter with classic Lambretta styling and modern city comfort.",
    imageUrl: "https://images.unsplash.com/photo-1622185135505-2d795003994a?auto=format&fit=crop&w=1200&q=80",
    features: ["Brand new unit", "Premium scooter", "Warranty processing", "Showroom release"],
    specs: { Engine: "275cc", Power: "24.8 hp", Torque: "24.5 Nm", Gearbox: "CVT", Fuel: "7 L", Weight: "165 kg" },
  },
  {
    id: "italjet-dragster-300-2026",
    sku: "VMH-BN-ITALJET-DRAGSTER-300-2026",
    name: "2026 Italjet Dragster 300",
    category: "Italjet",
    brand: "Italjet",
    model: "Dragster 300",
    condition: "Brand New",
    location: "Visayas Moto Hub Showroom",
    branch: "Cebu",
    status: "Ready",
    price: 398000,
    acquisitionCost: 0,
    quantity: 2,
    availableQuantity: 2,
    reservedQuantity: 0,
    description: "Brand-new Italjet performance scooter with aggressive styling and premium componentry.",
    imageUrl: "https://images.unsplash.com/photo-1609630875171-b1321377ee65?auto=format&fit=crop&w=1200&q=80",
    features: ["Brand new unit", "Performance scooter", "Warranty processing", "Showroom release"],
    specs: { Engine: "278cc", Power: "24 hp", Torque: "26 Nm", Gearbox: "CVT", Fuel: "9 L", Weight: "128 kg" },
  },
  {
    id: "ducati-desmo450-mx-2026",
    sku: "VMH-BN-DUCATI-DESMO450MX-2026",
    name: "2026 Ducati Desmo450 MX",
    category: "Ducati",
    brand: "Ducati",
    model: "Desmo450 MX",
    condition: "Brand New",
    location: "Visayas Moto Hub Showroom",
    branch: "Cebu",
    status: "Ready",
    price: 720000,
    acquisitionCost: 0,
    quantity: 1,
    availableQuantity: 1,
    reservedQuantity: 0,
    description: "Brand-new Ducati motocross machine available for serious riders through assisted inquiry and release coordination.",
    imageUrl: "https://images.unsplash.com/photo-1517846693594-1567da72af75?auto=format&fit=crop&w=1200&q=80",
    features: ["Brand new unit", "Pre-order assistance", "Dealer coordination", "Release support"],
    specs: { Engine: "450cc", Power: "TBA", Torque: "TBA", Gearbox: "5-speed", Fuel: "7.2 L", Weight: "TBA" },
  },
];

export const customers: Customer[] = [
  { id: "cus-001", fullName: "Rafa Santos", email: "rafa@example.com", contactNumber: "+63 917 000 1001", customerType: "Retail", address: "Quezon City" },
  { id: "cus-002", fullName: "Mika Reyes", email: "mika@example.com", contactNumber: "+63 917 000 1002", customerType: "Dealer", address: "Makati" },
  { id: "cus-003", fullName: "Northline Trading", email: "ops@northline.test", contactNumber: "+63 917 000 1003", customerType: "Corporate", address: "Cebu City" },
];

export const inquiries: Inquiry[] = [
  { id: "inq-001", productId: "cfmoto-450sr-s-2026", customerName: "Rafa Santos", email: "rafa@example.com", status: "New", message: "Can I reserve a brand-new 450SR S unit for showroom release?", createdAt: "2026-05-21" },
  { id: "inq-002", productId: "zeeho-ae8-s-plus-2026", customerName: "Northline Trading", email: "ops@northline.test", status: "Qualified", message: "Please send brand-new unit availability and release options.", createdAt: "2026-05-25" },
];

export const reservations: Reservation[] = [
  { id: "res-001", reservationNumber: "RSV-2026-0001", productId: "lambretta-x300-2026", customerName: "Mika Reyes", fee: 10000, expiryDate: "2026-06-05", status: "Confirmed" },
  { id: "res-002", reservationNumber: "RSV-2026-0002", productId: "ducati-desmo450-mx-2026", customerName: "Northline Trading", fee: 25000, expiryDate: "2026-06-01", status: "Pending" },
];
